import { Widget } from '@/app/store/dashboardSlice';

export const TEMPLATE_CONFIGS: Record<string, Widget[]> = {
  'template-crypto': [
    {
      id: `crypto-${Date.now()}-1`,
      name: 'Bitcoin Price',
      apiUrl: 'https://api.coingecko.com/api/v3/simple/price?ids=bitcoin&vs_currencies=usd&include_market_cap=true&include_24hr_change=true',
      selectedFields: ['bitcoin.usd', 'bitcoin.usd_market_cap', 'bitcoin.usd_24h_change'],
      displayMode: 'card',
      refreshInterval: 60,
      data: null,
      loading: false,
      error: null,
    },
    {
      id: `crypto-${Date.now()}-2`,
      name: 'Top 5 Cryptocurrencies',
      apiUrl: 'https://api.coingecko.com/api/v3/simple/price?ids=bitcoin,ethereum,binancecoin,cardano,solana&vs_currencies=usd&include_market_cap=true&include_24hr_change=true',
      selectedFields: ['bitcoin.usd', 'ethereum.usd', 'binancecoin.usd', 'cardano.usd', 'solana.usd'],
      displayMode: 'table',
      refreshInterval: 60,
      data: null,
      loading: false,
      error: null,
    },
    {
      id: `crypto-${Date.now()}-3`,
      name: 'Global Market Data',
      apiUrl: 'https://api.coingecko.com/api/v3/global?vs_currencies=usd',
      selectedFields: ['data.total_market_cap.usd', 'data.total_volume.usd', 'data.market_cap_percentage.btc'],
      displayMode: 'card',
      refreshInterval: 120,
      data: null,
      loading: false,
      error: null,
    },
  ],

  'template-stocks': [
    {
      id: `stock-${Date.now()}-1`,
      name: 'Market Indices Overview',
      apiUrl: 'https://api.coingecko.com/api/v3/global?vs_currencies=usd',
      selectedFields: ['data.total_market_cap.usd', 'data.total_volume.usd', 'data.market_cap_percentage.btc'],
      displayMode: 'card',
      refreshInterval: 300,
      data: {
        total_market_cap: '$1.2T',
        total_volume: '$85B',
        btc_dominance: '48.5%',
      },
      loading: false,
      error: null,
    },
    {
      id: `stock-${Date.now()}-2`,
      name: 'Top Cryptocurrencies',
      apiUrl: 'https://api.coingecko.com/api/v3/simple/price?ids=bitcoin,ethereum,binancecoin,ripple,cardano&vs_currencies=usd&include_market_cap=true',
      selectedFields: ['bitcoin.usd', 'ethereum.usd', 'binancecoin.usd', 'ripple.usd', 'cardano.usd'],
      displayMode: 'table',
      refreshInterval: 300,
      data: {
        bitcoin: { usd: 42350, usd_market_cap: 830000000000 },
        ethereum: { usd: 2350, usd_market_cap: 282000000000 },
        binancecoin: { usd: 615, usd_market_cap: 94000000000 },
        ripple: { usd: 2.45, usd_market_cap: 131000000000 },
        cardano: { usd: 0.95, usd_market_cap: 33000000000 },
      },
      loading: false,
      error: null,
    },
    {
      id: `stock-${Date.now()}-3`,
      name: 'Market Trends',
      apiUrl: 'https://api.coingecko.com/api/v3/simple/price?ids=bitcoin,ethereum,solana&vs_currencies=usd&include_24hr_change=true',
      selectedFields: ['bitcoin.usd_24h_change', 'ethereum.usd_24h_change', 'solana.usd_24h_change'],
      displayMode: 'chart',
      refreshInterval: 3600,
      data: {
        bitcoin: { usd_24h_change: 2.45 },
        ethereum: { usd_24h_change: 1.82 },
        solana: { usd_24h_change: 3.21 },
      },
      loading: false,
      error: null,
    },
  ],

  'template-forex': [
    {
      id: `forex-${Date.now()}-1`,
      name: 'Cryptocurrency Exchange Rates',
      apiUrl: 'https://api.coingecko.com/api/v3/simple/price?ids=ethereum,litecoin,ripple,dogecoin,polkadot&vs_currencies=eur,gbp,jpy',
      selectedFields: ['ethereum.eur', 'litecoin.gbp', 'ripple.jpy', 'dogecoin.eur', 'polkadot.gbp'],
      displayMode: 'table',
      refreshInterval: 600,
      data: {
        ethereum: { eur: 2100, gbp: 1890 },
        litecoin: { eur: 165, gbp: 148 },
        ripple: { eur: 2.20, gbp: 1.98 },
        dogecoin: { eur: 0.18, gbp: 0.16 },
        polkadot: { eur: 7.50, gbp: 6.75 },
      },
      loading: false,
      error: null,
    },
    {
      id: `forex-${Date.now()}-2`,
      name: 'Multi-Currency Tracker',
      apiUrl: 'https://api.coingecko.com/api/v3/simple/price?ids=bitcoin&vs_currencies=usd,eur,gbp,jpy,cad,aud',
      selectedFields: ['bitcoin.usd', 'bitcoin.eur', 'bitcoin.gbp', 'bitcoin.jpy', 'bitcoin.cad', 'bitcoin.aud'],
      displayMode: 'card',
      refreshInterval: 600,
      data: {
        USD: 42350,
        EUR: 39000,
        GBP: 34200,
        JPY: 6350000,
        CAD: 57800,
        AUD: 65300,
      },
      loading: false,
      error: null,
    },
    {
      id: `forex-${Date.now()}-3`,
      name: 'Crypto vs Fiat',
      apiUrl: 'https://api.coingecko.com/api/v3/global?vs_currencies=usd,eur,gbp',
      selectedFields: ['data.total_market_cap.usd', 'data.total_market_cap.eur', 'data.total_market_cap.gbp'],
      displayMode: 'chart',
      refreshInterval: 1800,
      data: {
        market_cap_usd: 1200000000000,
        market_cap_eur: 1100000000000,
        market_cap_gbp: 950000000000,
      },
      loading: false,
      error: null,
    },
  ],

  'template-custom': [
    {
      id: `custom-${Date.now()}-1`,
      name: 'Your Custom API',
      apiUrl: 'https://api.example.com/custom-data',
      selectedFields: ['data'],
      displayMode: 'card',
      refreshInterval: 300,
      data: {
        message: 'Connect your API to see live data here',
        status: 'Ready to receive data',
      },
      loading: false,
      error: null,
    },
  ],
};
